### ISSUE TITLE
Data missing from panels in Grafana

### ISSUE THREAD

**Issue by natalytvinova** [canonical/grafana-agent-operator#70] opened 2024-03-12 07:29 UTC
### Bug Description

Hi I deployed latest/edge rev 37 (for hosts and for containers separately) and related it to Openstack components as in the juju status provided. Unfortunately not all information appeared in some dashboards. It's hard to track, if those dashboards came from grafana-agent, but I'll start from here and if needed I will file a bug somewhere else. 
So the dashboards missing the data: 
- Host details: No data in all of the panels
-  System Resources: CPU spent seconds in guests, processes state, processes memory, PID number and limit, Interrupts detail, CPU time spent in user context, file descriptors, power supply, systemd panels
- [juju] Libvirt Metrics: no data at all
- [juju] OpenStack Hypervisor Overview: only cumulative memory usage present 
- [juju] OpenStack Overview: not data

Host details:
![Screenshot from 2024-03-12 13-14-23](https://github.com/canonical/grafana-agent-operator/assets/26149450/6971b3e6-d4c5-4e30-8ccb-7ffac7cd05d8)

System resources:
![Screenshot from 2024-03-12 13-10-00](https://github.com/canonical/grafana-agent-operator/assets/26149450/048b0e3e-9b52-4812-a1da-2778afd63326)
![Screenshot from 2024-03-12 13-07-53](https://github.com/canonical/grafana-agent-operator/assets/26149450/fce35d79-7e39-4943-97e7-055f57542473)
![Screenshot from 2024-03-12 13-06-53](https://github.com/canonical/grafana-agent-operator/assets/26149450/d3815274-99b8-448d-b755-12baa2e4c14b)
![Screenshot from 2024-03-12 13-05-21](https://github.com/canonical/grafana-agent-operator/assets/26149450/35eecc75-75b4-4bf9-8b27-1a65f6fd6291)
![Screenshot from 2024-03-12 13-04-58](https://github.com/canonical/grafana-agent-operator/assets/26149450/f69e3b7e-22da-4c13-967c-d2ef6a572707)
![Screenshot from 2024-03-12 13-03-03](https://github.com/canonical/grafana-agent-operator/assets/26149450/f52a7f5f-8d18-475e-8cf7-d236e1996790)

[juju] Libvirt Metrics: 
![Screenshot from 2024-03-12 14-43-55](https://github.com/canonical/grafana-agent-operator/assets/26149450/96c9e85f-f409-48bf-8c36-4458245e8731)

[juju] OpenStack Hypervisor Overview: 
![Screenshot from 2024-03-12 14-45-30](https://github.com/canonical/grafana-agent-operator/assets/26149450/cce2225f-475b-40bc-b83b-ea8965e115f7)

[juju] OpenStack Overview: 
![Screenshot from 2024-03-12 14-50-21](https://github.com/canonical/grafana-agent-operator/assets/26149450/04602cd1-aaaf-4301-9506-9eaaae0586a3)

### To Reproduce

Here is a juju status with all the relations: 
[final-juju-status.txt](https://github.com/canonical/grafana-agent-operator/files/14568738/final-juju-status.txt)
And COS bundle I used: 
[final-cos-bundle.txt](https://github.com/canonical/grafana-agent-operator/files/14568744/final-cos-bundle.txt)

### Environment

Openstack Yoga, details of the charm versions are provided in the juju status. 

### Relevant log output

```shell
-
```

**Comment by natalytvinova** [comment] 2024-04-19 14:12
We upgraded the charm to channel latest/edge revision 87, but the problem is still there

**Comment by ca-scribner** [comment] 2024-06-20 13:22
@natalytvinova do you still experience this?  If yes, can you give us links to a few dashboards you have trouble with so we can dig into it further?

**Comment by dstathis** [comment] 2024-07-11 13:00
Closing for now. If this issue persists, please feel free to reopen.

**Closed by dstathis** 2024-07-11 13:00 UTC

**Comment by natalytvinova** [comment] 2024-07-26 11:52
Hi team, sorry for a long reply. 

Some of them were related to prometheus openstack exporter, some to ceph charms. But what I still experience and I see it coming from the grafana-agent charm is these missing panels:
System Resources: CPU spent seconds in guests, processes state, processes memory, PID number and limit, Interrupts detail, CPU time spent in user context, file descriptors, power supply, systemd 

```
/etc/grafana/provisioning/dashboards# cat juju_grafana-agent_0def0c2.json | grep -i "System Resources"
...
 "time_options": ["5m", "15m", "1h", "6h", "12h", "24h", "2d", "7d", "30d"]}, "timezone": "browser", "title": "**System Resources**", "uid": "rYdddlPWk", "version": 9, "weekStart": ""}
...

**Comment by natalytvinova** [comment] 2024-07-26 11:55
Also just a general question, what does this reboot button mean? My guess maybe resources since last reboot of the node?
![image](https://github.com/user-attachments/assets/34cf9063-4aec-46bb-83aa-2542d4614305)

**Comment by lucabello** [comment] 2025-01-17 13:22
Those panels you specified show "no data" because the metrics that would populate those dashboards are not there.

This is not something malfunctioning, but rather one of:
1. the metric is never produced, and the dashboard panel should be removed;
2. the metric is produced only under certain circumstances, in which case we should a tooltip explaining what those are.

The problem is it's very hard to do (2); would you be happy with (1)?
